branch-defaults:
  main:
    environment: null
global:
  application_name: Credit_Card_default_predicition
  branch: main
  default_ec2_keyname: null
  default_platform: Python 3.9.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application